name: OWASP with Maven Docker Image Builder
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  owasp-maven-builder:
    runs-on: ubuntu-latest
    name: OWASP Maven Builder
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build latest images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nalusolutionsgmbh/owasp-maven-action:latest
          secrets: |
            "NVD_API_KEY=${{ secrets.NVD_API_KEY }}"
      - name: Update Published Date
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          echo "Last Published: $(date)" > published.md
          git commit -a -m "published"
          git push origin dev